<?php

namespace App\Http\Resources\Collections;

class UserCollection extends BaseCollection
{
    public function toFullResponse($request): array
    {
        return parent::toFullResponse($request); // TODO: Change the autogenerated stub
    }
}
